services:
  telemedizin-api-service:
    container_name: telemedizin-php-container
    build:
      context: ../..
      dockerfile: provisioning/development/php/dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../:/var/www/html
    depends_on:
      - telemedizin-db-service
    networks:
      - voidgrid

  telemedizin-db-service:
    image: postgres:15
    container_name: telemedizin-db-container
    environment:
      POSTGRES_USER: fuchs
      POSTGRES_PASSWORD: "schwarzwald"
      POSTGRES_DB: telemedizin
    volumes:
      - telemedizin-db-data:/var/lib/postgresql/data
    networks:
      - voidgrid

  telemedizin-nginx-service:
    image: nginx:stable-alpine
    container_name: telemedizin-nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - telemedizin-api-service
    networks:
      - voidgrid

networks:
  voidgrid:

volumes:
  telemedizin-db-data:
