name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Composer installieren
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Tests ausführen
        run: ./dev.sh test development
